---
title: "HW - Bike Data"
author: "Selimcan Biçer - Group 4"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, error=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h3> Installing Necesarry Libraries </h4>

```{r}
library(dplyr)
library(tidyverse)
library(janitor)
```

## Importing dataset
```{r}
# Importing dataset
bike <- readr::read_csv("bike_data.csv")
```

```{r}
# Looking for the first few observaiton
head(bike)
```

````{r}
# Looking for the last few observaiton
tail(bike)
````

````{r}
glimpse(bike)
````


````{r}
summary(bike)
````

````{r}
# Looking for the number of NA's
sum(is.na(bike))
````

````{r}
# Cleaning the column names which has blank character in it
bike <- bike |> 
  clean_names()

# Looking for the structure of the categorical variables
table(bike$seasons)
table(bike$holiday)
table(bike$functioning_day)
````

````{r}
# Looking for the structure of the rainfall and snowfall columns
table(bike$rainfall)
table(bike$snowfall)
````

````{r}
# Finding the days with rainfall or snawfall
bike_filtered <- bike |>
  filter(rainfall > 0 | snowfall > 0) |> 
  select(rainfall, snowfall)

rain_and_snow_days <- nrow(bike_filtered)
print(paste("Days with rainfall or snowfall:", rain_and_snow_days))
````

````{r}
# Removing dew point temperature data
bike_wo_dew <- bike |> select(-dew_point_temperature)
glimpse(bike_wo_dew)
````

````{r}
library(GGally)

bike_r <- sample(1:nrow(bike), size = 1500) # rows
bike_c <- c(2:4,sample(c(5:7,9:ncol(bike)),3)) # columns 
bike_data <- bike[bike_r,bike_c] 

bike_data |> 
  ggpairs()

````

````{r}
bike |> select(rented_bike_count:temperature) |> 
      ggpairs(upper = list(continous = wrap("cor", family="sans")))
````

````{r}

````


````{r}
bike_data |> 
  group_by(hour) |>                             
  summarise(a_rent = mean(rented_bike_count)) |>
  ungroup() |> 
  ggplot(aes(x = hour, y = a_rent)) +           
  geom_col(just = 0.5) +                        
  labs(
    title = "Average Rented Bike Count",
    x = "Hours of Day",
    y = "Average Rented Bike Count"
  ) + 
  theme_bw()

````

````{r}

library(corrplot)

bike_new <- bike |> select(-humidity, -wind_speed, -visibility, -dew_point_temperature, -solar_radiation)
bike_new |> 
    select_if(is.numeric) |>
    cor () |>
    corrplot( type = "upper",
            insig = "blank",
            diag = FALSE,
            addCoef.col = "grey40")

````

````{r}

````

````{r}

````

````{r}

````

````{r}

````

